import {
  Calendar,
  Plus,
  ShoppingCart,
  Trash,
  Wallet,
  Search,
  ChevronsLeftRight,
  ChevronsLeft,
  ChevronsRight,
  Pencil,
  Filter,
  CalendarDays,
  BadgeDollarSign,
  Car,
  Utensils,
  Tag,
  Coins,
  Home,
  Wifi,
  GraduationCap,
  Gamepad,
  Gift,
  Plane,
  PiggyBank,
  BookOpen,
  Briefcase,
  Fuel,
  Heart,
  Pill,
  Smartphone,
  Umbrella,
  Tv,
  Plug,
} from 'lucide-react';

export const iconMap = {
  calendar: Calendar,
  wallet: Wallet,
  cart: ShoppingCart,
  plus: Plus,
  trash: Trash,
  search: Search,
  chevrons: ChevronsLeftRight,
  chevronLeft: ChevronsLeft,
  chevronRight: ChevronsRight,
  pencil: Pencil,
  filter: Filter,
  calendarDays: CalendarDays,
  badgeDollarSign: BadgeDollarSign,
  utensils: Utensils,
  car: Car,
  tag: Tag,
  coins: Coins,
  home: Home,
  wifi: Wifi,
  graduationCap: GraduationCap,
  gamepad: Gamepad,
  gift: Gift,
  plane: Plane,
  piggyBank: PiggyBank,
  bookOpen: BookOpen,
  briefcase: Briefcase,
  fuel: Fuel,
  heart: Heart,
  pill: Pill,
  smartphone: Smartphone,
  umbrella: Umbrella,
  tv: Tv,
  plug: Plug,
} as const;

export type IconName = keyof typeof iconMap;
